In [1]:
import numpy as np
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print("Matrix A:\n", a)
print("Matrix B:\n", b)
sum_matrix = np.add(a, b)
print("Sum of A and B:\n", sum_matrix)
dot_product = np.dot(a, b)
print("Dot Product of A and B:\n", dot_product)
matrix_multiplication = np.matmul(a, b)
print("Matrix Multiplication of A and B:\n", matrix_multiplication)


Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
Sum of A and B:
 [[ 6  8]
 [10 12]]
Dot Product of A and B:
 [[19 22]
 [43 50]]
Matrix Multiplication of A and B:
 [[19 22]
 [43 50]]
